<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <StartupObject>Postgres.Embedded.Examples.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Postgres.Embedded\Postgres.Embedded.csproj" />
  </ItemGroup>

</Project>